resilience4j:
  circuitbreaker:
    instances:
      bookingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      paymentCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 15s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  
  ratelimiter:
    instances:
      bookingRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
      paymentRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
  
  retry:
    instances:
      bookingRetry:
        maxAttempts: 3
        waitDuration: 100ms
        exponentialBackoffMultiplier: 2
      paymentRetry:
        maxAttempts: 3
        waitDuration: 100ms
        exponentialBackoffMultiplier: 2
